project-alice-assistant/ProjectAlice

README.md
configSample.py
core/Initializer.py
core/user/UserManager.py
core/user/model/User.py
core/voice/model/TTS.py
modules/AliceCore/AliceCore.py
modules/AliceCore/talks/en.json

ttsLanguage, ttsType, and ttsVoice can be left blank
Defaults to 'en-US' and the first type and voice in the list
Also enabled per-user settings for TTS

Add TTS Language seperate from the active language

---

core/base/model/Module.py
core/console/AddCommand.py
core/console/ListCommand.py
core/console/UpdateCommand.py
core/device/DeviceManager.py
core/dialog/model/DialogSession.py
core/server/MqttManager.py

use Path for interface sinde it is already sometimes called with Path objects and others like AliceCore use path objects and convert them to a string to call it

use path for interface

---

core/commons/commons.py

I think it would be good to check whether the user is online when a exception is thrown aswell since the last online state might be 1min + runtime of the code in the decorated function old, so the user does not need any offline handling in the decorated function anymore.

improve online wrapper

---

core/base/model/Module.py

this allows modules to directly implement functions for each intent instead of overwriting the onMessage method. (can still be overwritten and used the same way as before aswell)
example: https://github.com/project-alice-powered-by-snips/ProjectAliceModules/pull/44

Action mapping

---

core/base/model/Module.py
core/commons/constants.py
core/voice/ASRManager.py
modules/Customisation/Customisation_sample.py

Reverts project-alice-powered-by-snips/ProjectAlice#85

Revert "Actions mapping"

---

core/Initializer.py
core/base/ModuleManager.py
core/base/model/ProjectAliceObject.py
core/commons/CommonsManager.py
core/commons/constants.py
main.py

Better versioning

---

core/commons/CommonsManager.py
core/commons/constants.py
core/util/DatabaseManager.py
core/util/Decorators.py
core/util/InternetManager.py
tests/unittests/commons/test_CommonsManager.py
tests/unittests/util/test_Decorators.py
tests/unittests/util/test_InternetManager.py

I did add test cases for the mqtt payload helper from the commonsManager. Since it failed a lot of them I fixed the helper. @Psychokiller1888 can you take a look at the test cases, whether you have a idea of other things that might go wrong and require handling?

Mqtt payload

---

core/base/model/Module.py

should fix #118 but I can not test right now since some other stuff throws

overwrite decoration

---

core/base/model/Module.py
core/base/model/ProjectAliceObject.py
core/dialog/model/DialogMapping.py
core/dialog/model/DialogSession.py
core/server/MqttManager.py

This moves the intentName into the DialogSession object

move intentName into dialogsession

---

core/voice/TalkManager.py

help skill developers finding errors

error logging added

---

core/base/model/AliceSkill.py
core/base/model/ProjectAliceObject.py

Reverts project-alice-assistant/ProjectAlice#185

Revert "use event funcs for type checking only"

---

core/asr/model/PocketSphinxASR.py

only every 10th result is send to prevent spamming

Update PocketSphinxASR.py - add intermediate results

---

core/interface/templates/alicewatch.html

Update page title from Snips to Alice watch. Sorry missed that one in the last PR

Page title update in alicewatch.html

---

core/device/DeviceManager.py

Add skillName column to devices table

---

core/base/model/ProjectAliceObject.py
core/util/TelemetryManager.py

Add Kwargs to Telemetry broadcast Message so event can be reacted to properly.

Add onGasHighAlert event.

---

core/base/model/ProjectAliceObject.py
core/util/TelemetryManager.py

Fixed wrong naming for Gas Alert in ProjectAliceObject.py
Added SiteId to kwargs of TelemetryManager.py

1.0.0 b2 Telemetry Update

---

core/util/TelemetryManager.py

replace " ,"  with " and "
dismiss if not correct :)

Phillip to review if this is what you meant ?

---

configTemplate.json
core/asr/model/GoogleAsr.py
core/base/SkillManager.py
core/interface/templates/devmode.html
core/util/Decorators.py
core/util/InternetManager.py

New setting for internet quality changing how the control if internet connectivity present works. Makes Alice react faster if internet is lost, reducing the lags for people with poorer internet connection

B4 experimental

---

core/interface/static/css/projectalice.css
core/interface/static/js/admin.js
core/interface/static/js/adminAuth.js
core/interface/static/js/alicewatch.js
core/interface/static/js/common.js
core/interface/static/js/devmode.js
core/interface/static/js/myHome.js
core/interface/static/js/skills.js
core/interface/static/js/syslog.js
core/interface/static/js/widgets.js
core/interface/templates/home.html

Reworking this completly broken z-indexing system

:construction: Reworking broken z-indexing

---

.github/workflows/pytest.yml
README.md
config-schema.json
configTemplate.json
core/base/ConfigManager.py
core/base/SuperManager.py
core/server/AudioServer.py
requirements.txt
requirements_test.txt

Dumping pyaudio in favor of sounddevice
./venv/bin/pip install sounddevice==0.4.1

:construction: experimenting with new audio package

---

core/dialog/DialogManager.py
core/dialog/DialogTemplateManager.py
core/util/TelemetryManager.py
system/manager/TalkManager/talks/en.json

Added a little more of a personal touch by adding the username to a couple of the initial notification message (if available).
EG: 
- "hey alice"
- "yes Mike ?"
Also Removed "what?" and replaced with a few more options for variety
Removed some of my test code from telemetry manager, accidentally commited it

Added a personal touch

---

core/webApi/model/MyHomeApi.py

Add some clarity to the missing icon error. Now reports the device name in issue and the path it was trying to look for 
Produces a sonar warning, Have tried to suppress it but doesn't seem successful

Add clarity to icon error

---

core/webApi/model/MyHomeApi.py

Prevent user from deleting locationId 1
Feel free to revert if this is not needed, but i feel it is :)

Prevent user from deleting location 1

---

core/device/DeviceManager.py
core/device/model/Device.py

DisplayName was still returning None. Changed self._data for self_deviceConfigs and all is well. Was this your intention ?

fix displayName returning None

---

core/Initializer.py

added missing pyyaml to the hermesLEdControl via initializer
Not tested, but suspect it's good to go

add pyyaml install to initializer

---

configTemplate.json

Config file change for the recent internet connection reporting feature PR

Option to stop internet connectivity reporting

---

system/manager/TalkManager/talks/en.json

Typo in TalkManager notUnderstoodEnd

fix: typo in TalkManager notUnderstoodEnd

---

system/manager/TalkManager/talks/en.json

Originally https://github.com/project-alice-assistant/ProjectAlice/pull/472 but this time for rc1
Minor talks correction originally https://github.com/project-alice-assistant/ProjectAlice/pull/472 this time against RC1
- [x Other, please describe:

Minor correct to TalkManager talks en.json
